### ISSUE TITLE
UKBB possible steps for row data laid out by Michael

### ISSUE THREAD

**Issue by jbpoline** [datalad/ukbiobank#6]
@mih : lmk if I missed anything
1. Dowload -> UKBB zip
2. DL save in branch incoming
3. DL add-archive in branch incoming-processed
    Note: this is to extract the zip - see add-archive DL command
4. git merge incoming-processed in master
5. DL drop all extracted
6. config [RIA](https://github.com/datalad/git-annex-ria-remote) special remote pointing to actual storing
7. DL publish onto storage
     Note: actual repo nees to be also pushed somewhere
8. throw away local clones 
9. create BIDS - code lives on super DS

**Comment by mih** [comment]
Everything until 4 is now implemented and merged into master.

9 is coming for a single participant in #13 

This rest is generic functionality that is available in https://github.com/datalad/git-annex-ria-remote at the moment, and individual PRs to merge it into DataLad proper are opened, such as https://github.com/datalad/datalad/pull/4124

I will close this issue, it has served its purpose.
